### ISSUE TITLE
Deferring surface init should imply additional flags

### ISSUE THREAD

**Issue by martty** [charles-lunarg/vk-bootstrap#27] opened 2020-04-19 06:16 UTC
- loading the swapchain extension
- require_present(false) (or the logic redone so that this is not required)

**Comment by charles-lunarg** [comment] 2020-04-19 06:36
Loading the swapchain extension definitely needs to be addressed, as its based on the presence of a 'VkSurfaceKHR` handle, which defering surface init means won't be set.
```cpp
std::vector<const char*> extensions = info.extensions_to_enable;
	if (info.surface != VK_NULL_HANDLE) extensions.push_back ({ VK_KHR_SWAPCHAIN_EXTENSION_NAME });
```
to 
```
std::vector<const char*> extensions = info.extensions_to_enable;
	if (info.surface != VK_NULL_HANDLE || info.defer_surface_init) extensions.push_back ({ VK_KHR_SWAPCHAIN_EXTENSION_NAME });
```

The issue with require_present is that it makes sure you can present from this physical device. Which is more to say, when I originally implemented it, I didn't see the connection and now should be able to disable checking for present support if defer_surface_init is true. However, that leaves anyone using the defered surface init with the possibility of using a gpu which doesn't support presentation.  Considering that deferring surface initialization means you can't actually perform any checks, it shouldn't be a problem realistically, but I just want that to be clear.

**Comment by charles-lunarg** [comment] 2020-04-19 06:55
I have pushed the fixes up to master. Can you confirm they work as intended?

**Comment by martty** [comment] 2020-04-19 07:13
I confirm they work. There is one more pitfall, though this may be covered by docs: in the deferred surface init case, you must manually query for a present queue, otherwise validation error messages (since vkGetPhysicalDeviceSurfaceSupportKHR is not called otherwise). Perhaps SwapchainBuilder could do this internally on the queue index passed in? Also would be an error check mechanism.

**Comment by charles-lunarg** [comment] 2020-04-19 07:47
When you create a swapchain builder with a vkb::Device, it queries the present index.
```cpp
SwapchainBuilder::SwapchainBuilder (Device const& device) {
	info.device = device.device;
	info.physical_device = device.physical_device.physical_device;
	info.surface = device.surface;
	auto present = device.get_queue_index (QueueType::present); //detail::get_present_queue_index, which calls vkGetPhysicalDeviceSurfaceSupportKHR
	auto graphics = device.get_queue_index (QueueType::graphics);
```
Meaning it should already be getting the present queue then as long as you stuff a VkSurfaceKHR inside the vkb::Device struct. Its a public member so its not limited by the API. 

If you are using the swapchain builder constructor that takes in the raw values (vkdevice, uint32 for queue indexes, & surface handle) then yes you'd need to manually query the present queue index.

The question then is, when you 'defer surface initialization', when should you supply the vk-bootstrap machinery with the surface handle? I don't like needing to give the vkb::Device struct a surface handle as thats counter intuitive. Maybe the swapchain constructor could only take a physical device, device, and surface, then get the queues automatically? That seems less brittle and more self contained. Actually, I like that a lot, and provides a nice alternative since the swapchain doesn't necessarily rely on the rest of vk-bootstrap to function.

**Comment by charles-lunarg** [comment] 2020-04-20 00:02
I added a new constructor for SwapchainBuilder that takes a `vkb::Device` and a `VkSurfaceKHR` which solves the issue of needing to manually set the surface handle of the `vkb::Device` struct. While that could of been documented, it is better to be explicit about it in the API.

**Comment by martty** [comment] 2020-04-20 18:59
Perfect! I think that is the best way to solve this. Thanks!

**Closed** 2020-04-20 19:11 UTC
