### ISSUE TITLE
Unable to compile on Ubuntu

### ISSUE THREAD

**Issue by ShenMian** [charles-lunarg/vk-bootstrap#100] opened 2021-12-25 09:20 UTC
OS: Ubuntu 20.04.3 LTS
Compiler: Clang 13.0.1
C++ Standard: C++20

I have tried to compile it on Windows and Ubuntu, but it only succeeded on Windows.
[Full build log](https://github.com/ShenMian/Graphics/runs/4597712621?check_suite_focus=true)

```
In file included from /home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrap.cpp:17:
In file included from /home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrap.h:28:
/home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrapDispatch.h:1911:131: error: unknown type name 'VkCopyAccelerationStructureModeKHR'; did you mean 'VkCopyAccelerationStructureModeNV'?
        void cmdCopyAccelerationStructureNV(VkCommandBuffer commandBuffer, VkAccelerationStructureNV dst, VkAccelerationStructureNV src, VkCopyAccelerationStructureModeKHR mode) const noexcept {
                                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                                         VkCopyAccelerationStructureModeNV
/usr/include/vulkan/vulkan_core.h:9321:3: note: 'VkCopyAccelerationStructureModeNV' declared here
} VkCopyAccelerationStructureModeNV;
  ^
In file included from /home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrap.cpp:17:
In file included from /home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrap.h:28:
/home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrapDispatch.h:2026:57: error: unknown type name 'VkImageViewAddressPropertiesNVX'
        VkResult getImageViewAddressNVX(VkImageView imageView, VkImageViewAddressPropertiesNVX* pProperties) const noexcept {
                                                               ^
/home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrapDispatch.h:3145:2: error: unknown type name 'PFN_vkGetRayTracingShaderGroupHandlesKHR'; did you mean 'PFN_vkGetRayTracingShaderGroupHandlesNV'?
        PFN_vkGetRayTracingShaderGroupHandlesKHR fp_vkGetRayTracingShaderGroupHandlesKHR = nullptr;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PFN_vkGetRayTracingShaderGroupHandlesNV
/usr/include/vulkan/vulkan_core.h:9482:30: note: 'PFN_vkGetRayTracingShaderGroupHandlesNV' declared here
typedef VkResult (VKAPI_PTR *PFN_vkGetRayTracingShaderGroupHandlesNV)(VkDevice device, VkPipeline pipeline, uint32_t firstGroup, uint32_t groupCount, size_t dataSize, void* pData);
                             ^
In file included from /home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrap.cpp:17:
In file included from /home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrap.h:28:
/home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrapDispatch.h:3175:2: error: unknown type name 'PFN_vkGetImageViewAddressNVX'; did you mean 'PFN_vkGetImageViewHandleNVX'?
        PFN_vkGetImageViewAddressNVX fp_vkGetImageViewAddressNVX = nullptr;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PFN_vkGetImageViewHandleNVX
/usr/include/vulkan/vulkan_core.h:7726:30: note: 'PFN_vkGetImageViewHandleNVX' declared here
typedef uint32_t (VKAPI_PTR *PFN_vkGetImageViewHandleNVX)(VkDevice device, const VkImageViewHandleInfoNVX* pInfo);
                             ^
In file included from /home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrap.cpp:17:
In file included from /home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrap.h:28:
/home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrapDispatch.h:556:46: error: unknown type name 'PFN_vkGetRayTracingShaderGroupHandlesKHR'; did you mean 'PFN_vkGetRayTracingShaderGroupHandlesNV'?
                fp_vkGetRayTracingShaderGroupHandlesKHR = (PFN_vkGetRayTracingShaderGroupHandlesKHR)procAddr(device, "vkGetRayTracingShaderGroupHandlesKHR");
                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                           PFN_vkGetRayTracingShaderGroupHandlesNV
/usr/include/vulkan/vulkan_core.h:9482:30: note: 'PFN_vkGetRayTracingShaderGroupHandlesNV' declared here
typedef VkResult (VKAPI_PTR *PFN_vkGetRayTracingShaderGroupHandlesNV)(VkDevice device, VkPipeline pipeline, uint32_t firstGroup, uint32_t groupCount, size_t dataSize, void* pData);
                             ^
In file included from /home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrap.cpp:17:
In file included from /home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrap.h:28:
/home/runner/work/Graphics/Graphics/Deps/vk-bootstrap/src/VkBootstrapDispatch.h:586:34: error: unknown type name 'PFN_vkGetImageViewAddressNVX'; did you mean 'PFN_vkGetImageViewHandleNVX'?
                fp_vkGetImageViewAddressNVX = (PFN_vkGetImageViewAddressNVX)procAddr(device, "vkGetImageViewAddressNVX");
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                               PFN_vkGetImageViewHandleNVX
/usr/include/vulkan/vulkan_core.h:7726:30: note: 'PFN_vkGetImageViewHandleNVX' declared here
typedef uint32_t (VKAPI_PTR *PFN_vkGetImageViewHandleNVX)(VkDevice device, const VkImageViewHandleInfoNVX* pInfo);
                             ^
6 errors generated.
```
How can I solve this problem? (I am not familiar with Vulkan)

**Comment by charles-lunarg** [comment] 2021-12-26 00:56
I can help you solve the bug right here and right now, but it won't fix the bug in vk-bootstrap. This is a 'mismatch Vulkan header' build. VkCopyAccelerationStructureModeKHR is the type found in never vulkan headers while VkCopyAccelerationStructureModeNV would exist in the old headers (since the NV type was introduced first). 
What you can do is install the latest vulkan headers on your system. This can be done in a few ways, either by manually installing the vulkan headers from the Vulkan-Headers repo, or by getting the up to date packages from LunarG (available here https://vulkan.lunarg.com/). I really like the packages but well, I'm biased :) 

The root of the problem is that the code is using `#if (defined(VK_NV_ray_tracing))` to guard against old headers, but... the is a type in that function which doesn't use the correct type. This will take some additional wrangling to fix on my end.

**Closed** 2022-02-06 03:43 UTC
Labels: bug
